# -*- coding: utf-8 -*-
"""lets grow more task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgK2-1UC7AqH6MAEZXsiqeGQXw6y3ggi
"""

import imageio.v3 as iio

filenames = ['/content/10 2.jpeg','/content/10.jpeg']
images = [ ]

for filename in filenames:
  images.append(iio.imread(filename))

iio.imwrite('team.gif', images, duration = 500, loop = 0)